# /etc/zsh/zlogout: system-wide .zlogout file for zsh(1).

ssh-agent -k

# when leaving the console clear the screen to increase privacy

if [ "$SHLVL" = 1 ]; then
    [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
fi

# vim: ft=sh fdm=marker fdc=3 fdl=0
