# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

# Completions
# https://github.com/zsh-users/zsh-completions
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

# for Deferred loading
# https://github.com/romkatv/zsh-defer
[plugins.zsh-defer]
github = "romkatv/zsh-defer"
[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

# https://github.com/zsh-users/zsh-autosuggestions
[plugins.zsh-autosuggestions]
apply = ["defer"]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

# https://github.com/junegunn/fzf-git.sh
[plugins.fzf-git]
apply = ["defer"]
github = "junegunn/fzf-git.sh"

# https://github.com/Aloxaf/fzf-tab
[plugins.fzf-tab]
apply = ["defer"]
github = "Aloxaf/fzf-tab"

# https://github.com/zsh-users/zsh-syntax-highlighting
[plugins.zsh-syntax-highlighting]
apply = ["defer"]
github = "zsh-users/zsh-syntax-highlighting"

# https://github.com/romkatv/powerlevel10k
[plugins.powerlevel10k]
apply = ["defer"]
github = "romkatv/powerlevel10k"
